"""
WHY THIS WAS CHOSEN:
We define structured Pydantic schemas for the API boundaries and internal streaming events.
This guarantees type safety, enforces consistent API contracts, and simplifies serialization
between the orchestrator and the HTTP streaming layers.
"""

from typing import List, Optional

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Schema for incoming client chat requests."""
    message: str = Field(..., description="The user's query.")
    session_id: Optional[str] = Field(None, description="Optional session tracking identifier.")


class Citation(BaseModel):
    """Metadata detailing the source of a retrieved context chunk."""
    file: str = Field(..., description="Source file path.")
    layer: str = Field(..., description="Document layer (identity, design, artifact).")
    project: str = Field(..., description="Canonical project ID.")


class BaseStreamEvent(BaseModel):
    """Base schema for typed streaming events yielded by the Orchestrator."""
    event: str = Field(..., description="The event type discriminator.")


class StreamTokenEvent(BaseStreamEvent):
    """Event containing a generated text token."""
    event: str = "token"
    token: str = Field(..., description="A chunk of text generated by the model.")


class StreamErrorEvent(BaseStreamEvent):
    """Event containing error metadata."""
    event: str = "error"
    code: str = Field(..., description="Error code identifier.")
    message: str = Field(..., description="Human-readable explanation of the failure.")


class StreamCitationsEvent(BaseStreamEvent):
    """Event containing retrieved citations for the response."""
    event: str = "citations"
    citations: List[Citation] = Field(..., description="List of source citations used to construct the response.")
